# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mob' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mob
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  target 'mob-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'mobTests' do
    inherit! :search_paths
    # Pods for testing
  end

end